#visiulisation
path_to_predictions: out/predictions/result_world_cmip6_wind.csv

plots_dir: out/visual_eobs27

vis_cmip_var: sfcWindmax
vis_eobs_var: fg

path_to_norm_values_cmip: src/utils/norm_values.py
quantile_gt: 0.96
quantile_cmip: 0.85

gt_data_folder: data/dataset-insitu-gridded-observations-europe-0ddfc2ac-7eb7-48af-b527-bdd5be538903/

timestamp: '2018-06-06' 

vis_lat_min: 39.5
vis_lat_max: 70.5
vis_lon_min: -8.5
vis_lon_max: 42.5
gt_res: 0.25