wind_risk_threshold: 20
use_elevation: false

time_start: '2018-06-06'
time_end: '2018-12-12'

lat_min: -90
lat_max: 90
lon_min: -180
lon_max: 180 

interpolation_res: 0.2           #if None - does not apply interpolation

num_workers_eval: 16
batch_size_test: 120 
distributed_test: false
strategy: ddp
gpu_num: 1

save_kml: false                   #if false, saves to csv

data_dir: data/cmip6_world2/      # directory to get climate files for test and inference
target_data_file: target.parquet  # target data file in data_dir for training for test and inference

path_to_checkpoint: /trinity/home/v.morozov/WindN/out/2023-08-24/23-04-36/epoch=5-step=15132.ckpt
path_to_predictions: out/predictions/result_world_cmip6.csv
output_file: out/predictions/output_file_world_cmip6      #format is chosen from `save_kml` boolean attribute
cmip_type: CMIP6




