---
experiment_name: "cmip5_toy_reg_w_naivemode20x42_max"
project_name: "Wind-speed-regression"
target_type: "wind_ms"

data_dir: "./data_mounted/cmip5_toy"
path_to_prepared_target_data: "/app/wind/data_mounted/cmip5_world2/target.parquet"
path_to_means: "./data_mounted/cmip5_toy/normalization_values_mean.npy"
path_to_std: "./data_mounted/cmip5_toy/normalization_values_std.npy"

model_name: WindNet5x28
half_side_size: 5
time_window: 29 # odd only 
time_freq: 7
target_threshold: 20
target_max: 68.94
target_min: 0.0

min_height: -10
max_height: 800
train_coords:
  lat_min: 43.62
  lat_max: 62.23
  lon_min: 36.68
  lon_max: 63.20

test_coords:
  lat_min: 43.62
  lat_max: 62.23
  lon_min: 36.68
  lon_max: 63.20
  
variables:
- sfcWindmax
- sfcWind
- pr
- psl
- tasmax
- tasmin
time_limits:
- '2000-01-01'
- '2020-11-14'
start_of_test: '2008-01-01'

batch_size: 180
learning_rate: 0.0003
weight_decay: 0.0001
max_epoch: 5
#Annealing steps
warmup_steps: 200

optimizer_name: "Adam"
scheduler_name: "OneCycleLR"
loss_name: "MSELoss"

num_workers: 0
gpu_num: 1
data_in_ram: false