---
experiment_name: "cmip5_binary_world"

data_dir: "./data/cmip5_world"
path_to_prepared_target_data: "./data/cmip5_world/target.parquet"
path_to_prepared_stations: "./data/cmip5_world/stations.parquet"
path_to_means: "./data/cmip5_world/normalization_values_mean.npy"
path_to_std: "./data/cmip5_world/normalization_values_std.npy"
logging_level: INFO

half_side_size: 12
time_window: 28
min_height: -10
max_height: 800
train_coords:
  lat_min: -48.38
  lat_max: 80.52
  lon_min: -179.12
  lon_max: 180.45
test_coords:
  lat_min: 43.62
  lat_max: 62.23
  lon_min: 36.68
  lon_max: 63.20
variables:
- sfcWindmax
- sfcWind
- pr
- psl
- tasmax
- tasmin
time_limits:
- '1950-01-01'
- '2020-11-14'
start_of_test: '2008-01-01'
speed_th: 20
batch_size: 1500
learning_rate: 0.0004
max_epoch: 200
threshold: 0.5
