---
experiment_name: "cmip6_highres_test"
make_climate_data: true
make_normalization: false #will be taken from train
make_cleaned_weather_data: false
make_target: false
load_normalization: true

paths_to_climate_files_folders: 
- "./data/cmip/MRI-highres_H"

path_to_elevation: "data/cmip/elevation/elevation.nc"
path_to_weather_stations: 'data/weatherstation_data/'
data_dir: "data/cmip6_highres_infer_test/" # the rest will be saved in this directory

prepared_target_data_name: "target.parquet"
prepared_stations_name: "stations.parquet"
path_to_folder_with_norm_for_infer: "data/cmip6_highres_test" # channel-wise normalization values (mean and std) will be copied from this folder)
normalization_values_name: "normalization_values" # _mean.npy, _std.npy, will be added to the name
saved_normalized: true
precision: 16

min_height: -10
max_height: 800
spatial_crop: False
train_coords:
  lat_min: 66.27
  lat_max: 69.67
  lon_min: 28.83
  lon_max: 41.02

variables:
- sfcWindmax
- sfcWind
- pr
- psl
- tasmax
- tasmin
time_limits:
- '2024-01-01'
- '2024-06-01'
start_of_test: '2024-03-01'

half_side_size: 20
pad_data: false
target_column: 
- "max_speed"