---
experiment_name: cmip5world
make_climate_data: False
make_normalization: False
make_cleaned_weather_data: False
make_target: true

paths_to_climate_files_folders: 
- "/home/teshbek/Datasets/cmip5_orig/rcp45/"

path_to_elevation: "data_mounted/cmip/elevation/elevation.nc"
path_to_weather_stations_data: "data_mounted/weather_stations/data_meteo_full.parquet"
path_to_weather_station_list: "data_mounted/weather_stations/weatherstation_list.json"
path_to_allowed_stations: "configs/splits/allowed_stations.txt"

path_to_world_weather_stations_data: "data_mounted/weather_stations/world_stations_25_days_6_months.parquet"

path_to_prepared_data_dir: "data_mounted/cmip5_world/" # the resw will be saved in this directory
prepared_target_data_name: "target_temp.parquet"
normalization_values_name: "normalization_values" # _mean.npy, _std.npy, will be added to the name
min_height: -10
max_height: 300
train_coords:
  lat_min: -48.38
  lat_max: 80.52
  lon_min: -179.12
  lon_max: 180.45
variables:
- sfcWindmax
- sfcWind
- pr
- psl
- tasmax
- tasmin
time_limits:
- '1950-01-01'
- '2020-11-14'
start_of_test: '2008-01-01'
half_side_size: 7
time_window: 28
speed_th: 20
target_column: 
- "avg_temp"