---
experiment_name: cmip5world
make_climate_data: true
make_normalization: true
make_cleaned_weather_data: false
make_target: false

paths_to_climate_files_folders: 
- '/home/teshbek/Datasets/cmip5_orig/rcp45/'

path_to_weather_stations_data: data_mounted/weatherstation_data
data_dir: data_mounted/cmip5_world3/ # the rest will be saved in this directory

prepared_target_data_name: target.parquet
prepared_stations_name: stations.parquet

saved_normalized: false #only save to float16 with saved_normalized=true 
precision: 32 # 32 

spatial_crop: False
train_coords:
  lat_min: -88.0
  lat_max: 88.0
  lon_min: -179.0
  lon_max: 180.45

variables:
- sfcWindmax
- sfcWind
- pr
- psl
- tasmax
- tasmin
time_limits:
- '1950-01-01'
- '2020-11-14'
start_of_test: '2008-01-01'

half_side_size: 20
pad_data: false
target_column: 
- 'max_speed'
# - 'avg_speed'
# - 'avg_temp'
# - 'sea_level_pressure'
# - 'station_level_pressure'
# - 'dew_point_temp'