---
experiment_name: cmip5world
make_climate_data: true
make_normalization: true
make_cleaned_weather_data: false
make_target: false
load_normalization: false

paths_to_climate_files_folders: 
- data/cmip5_world2

path_to_weather_stations_data: data/weatherstation_data
data_dir: data/cmip5_world3/ # the rest will be saved in this directory

saved_normalized: true #only save to float16 with saved_normalized=true 
precision: 16 # 32 

spatial_crop: False
train_coords:
  lat_min: -88.0
  lat_max: 88.0
  lon_min: -179.0
  lon_max: 180.45

variables:
- sfcWindmax
- sfcWind
- pr
- psl
- tasmax
- tasmin
time_limits:
- '1950-01-01'
- '2020-11-14'
start_of_test: '2008-01-01'

half_side_size: 20
pad_data: false
target_column: 
- max_speed