---
experiment_name: cmip6world
make_climate_data: false
make_normalization: false
make_cleaned_weather_data: true
make_target: true
load_normalization: false

paths_to_climate_files_folders: 
- './data/cmip/MRI-highres_H'

path_to_weather_stations: 'data/weatherstation_data/'
data_dir: data/cmip6_world/ # the rest will be saved in this directory

prepared_target_data_name: target.parquet
prepared_stations_name: stations.parquet

saved_normalized: true #only save to float16 with saved_normalized=true 
precision: 16 # 32 

spatial_crop: False
train_coords:
  lat_min: -89.0
  lat_max: 89.0
  lon_min: -179.5
  lon_max: 180.45
min_height: -10
max_height: 800

variables:
- sfcWindmax
- sfcWind
- pr
- psl
- tasmax
- tasmin
time_limits:
- '1950-01-01'
- '2023-11-14'
start_of_test: '2008-01-01'

half_side_size: 20
pad_data: false
target_column: 
- 'max_speed'
# - 'avg_speed'
# - 'avg_temp'
# - 'sea_level_pressure'
# - 'station_level_pressure'
# - 'dew_point_temp'