defaults:
  - raw: cmip6_elevation_paths              # paths to raw data to prepare dataset
  - process: cmip6_elevation_dataset        # dataset processing configuration
  - train: train_WindNetElev83x41_distributed.yaml  # train configuration and data load configuration
  - eval: test_WindNetElev83x41.yaml             # test and eval configuration 

experiment_name: cmip6_reg_elev
project_name: Wind-speed-regression
target_type: wind_ms #*
cmip_type: CMIP6 #*

model_name: WindNetElev83x41  # {name}{time_window}x{half_side_size}
time_window: 28               # must match model, odd only
half_side_size: 47            # must match model, odd only

start_date: '2019-01-30'                   #for eval only
end_date: '2019-03-31'


#* have no effect, just info 
