defaults:
  - raw: cmip6_elevation_paths    # paths to raw data to prepare dataset
  - process: cmip6_dataset        # dataset processing configuration
  - train: train_WindNet27x47     # train configuration and data load configuration
  - eval: test_WindNet27x47.yaml

experiment_name: cmip6_lightconv_2vars_quantile
project_name: Wind-speed-regression
target_type: wind_ms #*
cmip_type: CMIP6 #*

model_name: WindNet27x47  # {name}{time_window}x{half_side_size}
time_window: 27               # must match model, odd only
half_side_size: 47            # must match model, odd only

start_date: '2018-12-06'                   #for eval only
end_date: '2018-12-12'
