---
experiment_name: cmip5_lrsch_reg_w_naivemode21x41_max
make_climate_data: true
make_normalization: true
make_cleaned_weather_data: false
make_target: false

paths_to_climate_files_folders: 
- '/home/teshbek/Datasets/cmip5_orig/rcp45/'

path_to_weather_stations_data: data_mounted/weatherstation_data
data_dir: data_mounted/cmip5_world_infer/ # the rest will be saved in this directory
path_to_prepared_target_data: ./data_mounted/cmip5_world3/target.parquet

saved_normalized: false #only save to float16 with saved_normalized=true 
precision: 32 # 32 
project_name: Wind-speed-regression
target_type: wind_ms
checkpoint_path: 'outputs/epoch=0-step=5505.ckpt'

model_name: WindNet20x41
normalize: false

target_threshold: 20

spatial_crop: False
train_coords:
  lat_min: 43.62
  lat_max: 62.23
  lon_min: 36.68
  lon_max: 63.20
  
time_limits:
- '2018-01-01'
- '2020-11-14'

start_of_test: false #false means all data will be used for mean, std calulation 
variables:
- sfcWindmax
- sfcWind
- pr
- psl
- tasmax
- tasmin

batch_size: 250
num_workers: 4
gpu_num: 1
distributed: false
num_nodes: 1
strategy: 'ddp'

