---
experiment_name: "cmip6_highres_infer"
project_name: "Wind-speed-regression"
target_type: "wind_ms"

data_dir: "./data_mounted/cmip6_highres_infer_test"
path_to_prepared_target_data: "./data_mounted/cmip6_highres_infer_test/target.parquet"
path_to_prepared_stations: "./data_mounted/cmip6_highres_infer_test/stations.parquet"

model_name: WindNet20x41
normalize: false
precision: 32 # "16-mixed" "bf16-mixed"
half_side_size: 20
time_window: 41  # odd only
time_freq: 1
target_threshold: 25
target_max: 68.94
target_min: 0.0

min_height: -10
max_height: 800
train_coords:
  lat_min: 66.27
  lat_max: 69.67
  lon_min: 28.83
  lon_max: 41.02

test_coords:
  lat_min: 43.62
  lat_max: 62.23
  lon_min: 36.68
  lon_max: 63.20

variables:
- sfcWindmax
- sfcWind
- pr
- psl
- tasmax
- tasmin
time_limits:
- '2024-01-01'
- '2024-03-01'
start_of_test: '2024-01-01'

batch_size: 180
learning_rate: 0.0003
weight_decay: 0.0001
max_epoch: 5
#Annealing steps
warmup_steps: 200

optimizer_name: "Adam"
scheduler_name: "OneCycleLR"
loss_name: "MSELoss"
path_to_checkpoint: "2023-06-26/13-21-17/on_exception.ckpt" #will be searched within `outputs` folder

num_workers: 4
gpu_num: 2
data_in_ram: true