model_name: Linear83x5            # Have no effect
use_elevation: true
normalize: false                  # If you processed data with Precision 16 then data is already normalized, use False
time_agg_window: 28               # Range in days, used to calculate maximum for this range of day of target
time_freq: 28                     # Get sample from target every `time_freq` days
target_threshold: 20              # Threshold is used to estimate classification metrics and curves

data_dir: data/cmip6_world/       # Folder to get climate files for training
target_data_file: target.parquet  # Prepared with `process.py` target data file in data_dir for training

start_time: '2005-01-01'          # Time limits
end_time: '2009-12-12'
start_of_test: '2008-01-01'

batch_size: 200
learning_rate: 0.009
weight_decay: 0.0001
max_epoch: 2


optimizer_name: 'AdamW'
scheduler_name: 'LinearLR'
loss_name: 'MSELoss'

num_workers: 0
gpu_num: 1
distributed: false
num_nodes: 1
strategy: 'ddp'

log_every_n_steps: 100 