make_tmp_target_file: False

use_elevation: true
in_chans: 5               # 4 CMIP6 vars + 1 elevation channel
normalize: false

time_agg_window: 28
time_freq: 14
target_threshold: 15.0
abs_wind_threshold: 15.0

data_dir: data/cmip6_world/
target_data_file: target.parquet

start_time: '2000-01-01'
end_time: '2024-12-31'
start_of_test: '2023-01-01'

variables:
- sfcWindmax
- pr
- tasmax
- tasmin

spatial_crop: false
lat_min: 30
lat_max: 50
lon_min: -30
lon_max: 40

batch_size: 32
learning_rate: 0.0001
weight_decay: 0.0001
max_epoch: 100

optimizer_name: 'AdamW'
scheduler_name: 'LinearLR'
loss_name: 'BCELoss'

num_workers: 8
gpu_num: 1
distributed: false
num_nodes: 1
strategy: 'auto'

limit_train_batches: 5000
limit_val_batches: 1000

log_every_n_steps: 50

test_only: false
ckpt_path: null

cache:
  use_cached_padding: false
  pad_crop_data_path: "data/cache/cmip6_pad_crop_data.npy"
  shift_data_path: "data/cache/cmip6_shift_data.pkl"
