model_name: WindNet28x47 # have no effect
make_tmp_target_file: False

use_elevation: false
normalize: false      # precision 16 is already normalized
time_agg_window: 36   # range in days, used to calculate maximum for every day of target
time_freq: 16         # get sample from target every {time_freq} days
target_threshold: 20

data_dir: data/cmip6_world2       # directory to get climate files for training
target_data_file: target.parquet  # target data file in data_dir for training

start_time: '1998-01-01'
end_time: '2008-12-31'
start_of_test: '2000-01-01'

batch_size: 64
learning_rate: 0.009
weight_decay: 0.0004
max_epoch: 8


optimizer_name: 'AdamW'
scheduler_name: 'OneCycleLR'
loss_name: 'MSELoss'

num_workers: 7
gpu_num: 8
distributed: true
num_nodes: 1
strategy: 'ddp'

log_every_n_steps: 100 