model_name: WindNet41x41 # have no effect
make_tmp_target_file: False

use_elevation: false
normalize: false      # precision 16 is already normalized
time_agg_window: 36   # range in days, used to calculate maximum for every day of target
time_freq: 28         # get sample from target every {time_freq} days
target_threshold: 20

data_dir: data/cmip5_world3/      # directory to get climate files for training
target_data_file: target.parquet  # target data file in data_dir for training
       
start_time: '2005-01-01'
end_time: '2023-12-12'
start_of_test: '2008-01-01'

batch_size: 10
learning_rate: 0.009
weight_decay: 0.0001
max_epoch: 2


optimizer_name: 'AdamW'
scheduler_name: 'LinearLR'
loss_name: 'MSELoss'

num_workers: 10
gpu_num: 1
distributed: false
num_nodes: 1
strategy: 'ddp'

log_every_n_steps: 100 