make_tmp_target_file: False

use_elevation: false
normalize: false      # precision 16 is already normalized

time_agg_window: 28   # range in days, used to calculate maximum for every day of target
time_freq: 14         # get sample from target every {time_freq} days
target_threshold: 10  # m/s (was 20 knots ≈ 10.3 m/s, now data is in m/s)

data_dir: data/cmip6_world/
target_data_file: target.parquet

start_time: '2000-01-01'
end_time: '2024-12-31'
start_of_test: '2023-01-01'   # train 2000-2020, val 2021-2022, test 2023-2024

variables:
- sfcWindmax
- pr
- tasmax
- tasmin

spatial_crop: false
lat_min: 30
lat_max: 50
lon_min: -30
lon_max: 40

batch_size: 16
learning_rate: 0.0001
weight_decay: 0.0001
max_epoch: 100

optimizer_name: 'AdamW'
scheduler_name: 'LinearLR'
loss_name: 'BCELoss'

num_workers: 0
gpu_num: 1
distributed: false
num_nodes: 1
strategy: 'ddp'

# limit_train_batches: 5000   # ~56 min/epoch, 8-9 epochs overnight
# limit_val_batches: 1000     # ~11 min validation

log_every_n_steps: 10

test_only: false
ckpt_path: 'mlruns/680925330068273108/0307a5d955cf4cabbfce7175f20e3d5b/artifacts/model/checkpoints/epoch=1-step=1000/epoch=1-step=1000.ckpt'

cache:
  use_cached_padding: false
  pad_crop_data_path: "data/cache/cmip6_pad_crop_data.npy"
  shift_data_path: "data/cache/cmip6_shift_data.pkl"
